=== dolan1090/compumess/custom/plugins/SwagCommercial/src/B2B/EmployeeManagement/Resources/Schema/Xml/employee-route-access-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="routes">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="denied" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element name="allowed" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dolan1090/compumess/custom/plugins/SwagCommercial/src/B2B/EmployeeManagement/Resources/config/employee_route_access.xml
<?xml version="1.0" encoding="utf-8"?>
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Schema/Xml/employee-route-access-1.0.xsd">
    <denied>store-api.account.change-profile</denied>
    <denied>store-api.account.change-email</denied>
    <denied>store-api.account.change-language</denied>
    <denied>store-api.account.change-password</denied>
    <denied>store-api.account.set.payment-method</denied>
    <denied>store-api.account.customer</denied>
    <denied>store-api.account.address.delete</denied>
    <denied>store-api.account.customer.delete</denied>
    <denied>store-api.account.order.single.download</denied>
    <denied>store-api.account.address.list.get</denied>
    <denied>store-api.account.address.change.default.shipping</denied>
    <denied>store-api.account.address.change.default.billing</denied>
    <denied>store-api.account.address.create</denied>
    <denied>store-api.account.address.update</denied>
    <denied>store-api.newsletter.recipient</denied>

    <allowed>store-api.account.login</allowed>
    <allowed>store-api.account.logout</allowed>
    <allowed>store-api.account.register</allowed>
    <allowed>store-api.account.register.confirm</allowed>
    <allowed>store-api.account.customer.recovery.is.expired</allowed>
    <allowed>store-api.account.recovery.password</allowed>
    <allowed>store-api.account.recovery.send.mail</allowed>
    <allowed>store-api.account.business-partner.employee.confirm.password</allowed>
    <allowed>store-api.account.employee.recovery.is.expired</allowed>
</routes>
